[WIP] Add the support of custom user client cert generation
cockroachdb/helm-charts pull request #140
Opened 2021-07-22 08:53 UTC by prafull01

2021-07-30 19:35 UTC, keith-mcclellan requested changes
Please add some additional comments for the new functions, otherwise LGTM

2021-07-30 19:35 UTC, keith-mcclellan commented on pkg/generator/generate_cert.go
> +func (rc *GenerateCert) ClientCertGenerate(ctx context.Context, namespace string) error {
Can I get some comments here please

2021-07-30 19:35 UTC, keith-mcclellan commented on pkg/generator/generate_cert.go
> +func (rc *GenerateCert) LoadCASecret(ctx context.Context, namespace string) error {
Please put a code comment here as well

2021-07-30 20:31 UTC, prafull01 commented on pkg/generator/generate_cert.go
> +func (rc *GenerateCert) ClientCertGenerate(ctx context.Context, namespace string) error {
done

2021-07-30 20:32 UTC, prafull01 commented on pkg/generator/generate_cert.go
> +func (rc *GenerateCert) LoadCASecret(ctx context.Context, namespace string) error {
done

2021-08-02 13:30 UTC, keith-mcclellan approved these changes

2021-08-02 13:30 UTC, merged